export const TEAM_NAME_MAP: Record<string, string> = {
  "Greater Western Sydney": "GWS Giants",
  GWS: "GWS Giants",
  "GWS GIANTS": "GWS Giants",
  "Brisbane Bears": "Brisbane Lions",
  Brisbane: "Brisbane Lions",
  Footscray: "Western Bulldogs",
  "Sydney Swans": "Sydney",
  "Geelong Cats": "Geelong",
  "Adelaide Crows": "Adelaide",
  "West Coast Eagles": "West Coast",
  "Gold Coast SUNS": "Gold Coast",
  "Gold Coast Suns": "Gold Coast",
};

export const VENUE_NAME_MAP: Record<string, string> = {
  "M.C.G.": "MCG",
  "S.C.G.": "SCG",
  Docklands: "Marvel Stadium",
  "Etihad Stadium": "Marvel Stadium",
  "GMHBA Stadium": "Kardinia Park",
  "Manuka Oval": "Manuka Oval",
  "Corroboree Group Oval Manuka": "Manuka Oval",
  "Blundstone Arena": "Blundstone Arena",
  "Bellerive Oval": "Blundstone Arena",
  "Sydney Showground": "Sydney Showground",
  "ENGIE Stadium": "Sydney Showground",
  "GIANTS Stadium": "Sydney Showground",
  "Stadium Australia": "Accor Stadium",
  "ANZ Stadium": "Accor Stadium",
  "Cazaly's Stadium": "Cazalys Stadium",
  "TIO Stadium": "TIO Stadium",
  "Marrara Oval": "TIO Stadium",
  "TIO Traeger Park": "Traeger Park",
  "Mars Stadium": "Mars Stadium",
  "Eureka Stadium": "Mars Stadium",
  "People First Stadium": "Carrara",
  "Heritage Bank Stadium": "Carrara",
  Carrara: "Carrara",
  "Metricon Stadium": "Carrara",
  "Perth Stadium": "Perth Stadium",
  "Optus Stadium": "Perth Stadium",
  Gabba: "Gabba",
  "The Gabba": "Gabba",
  "York Park": "UTAS Stadium",
  "UTAS Stadium": "UTAS Stadium",
  "University of Tasmania Stadium": "UTAS Stadium",
  "Jiangwan Stadium": "Jiangwan Stadium",
  "Traeger Park": "Traeger Park",
  "Riverway Stadium": "Riverway Stadium",
  "Norwood Oval": "Norwood Oval",
};

export const COMPETITION_CODE = "AFLM";
export const MIN_PAV_YEAR = 1998;
