import type { Env } from "../types";

/**
 * Acquires the shared cron/admin operation lease when it is free or stale.
 *
 * @param env - Worker bindings.
 * @param holder - Opaque holder identifier generated by the caller.
 * @returns Whether this caller acquired the lease.
 */
export async function acquireOperationLease(env: Env, holder: string): Promise<boolean> {
  const result = await env.DB.prepare(
    `UPDATE sync_lease SET holder = ?1, acquired_at = datetime('now')
     WHERE id = 1 AND (holder IS NULL OR acquired_at < datetime('now', '-10 minutes'))`,
  )
    .bind(holder)
    .run();
  return result.meta.changes === 1;
}

/**
 * Releases the shared operation lease only when this caller still owns it.
 *
 * @param env - Worker bindings.
 * @param holder - Opaque holder identifier used to acquire the lease.
 */
export async function releaseOperationLease(env: Env, holder: string): Promise<void> {
  await env.DB.prepare(
    "UPDATE sync_lease SET holder = NULL, acquired_at = NULL WHERE id = 1 AND holder = ?1",
  )
    .bind(holder)
    .run();
}
