export function getSchemaInfo() {
  return {
    database: {
      engine: "SQLite (Cloudflare D1)",
      tables: {
        competitions: "id INTEGER PRIMARY KEY, code TEXT, name TEXT",
        seasons:
          "id INTEGER PRIMARY KEY, competition_id INTEGER REFERENCES competitions(id), year INTEGER",
        teams:
          "id INTEGER PRIMARY KEY, name TEXT, abbreviation TEXT, competition_id INTEGER REFERENCES competitions(id)",
        venues: "id INTEGER PRIMARY KEY, name TEXT",
        players: [
          "id INTEGER PRIMARY KEY, first_name TEXT, surname TEXT, external_id TEXT,",
          "external_afl_player_id TEXT,",
          "date_of_birth TEXT, height_cm INTEGER, weight_kg INTEGER, is_retired INTEGER",
        ].join(" "),
        matches: [
          "id INTEGER PRIMARY KEY, season_id INTEGER REFERENCES seasons(id),",
          "round TEXT, round_number INTEGER, round_type TEXT,",
          "date TEXT, local_time TEXT,",
          "venue_id INTEGER REFERENCES venues(id),",
          "home_team_id INTEGER REFERENCES teams(id),",
          "away_team_id INTEGER REFERENCES teams(id),",
          "home_goals INTEGER, home_behinds INTEGER, home_points INTEGER,",
          "away_goals INTEGER, away_behinds INTEGER, away_points INTEGER,",
          "margin INTEGER, attendance INTEGER,",
          "weather_temp_c REAL, weather_type TEXT,",
          "external_afltables_id TEXT, external_fryzigg_id TEXT,",
          "external_afl_id TEXT,",
          "home_rushed_behinds INTEGER, away_rushed_behinds INTEGER,",
          "home_minutes_in_front INTEGER, away_minutes_in_front INTEGER,",
          "home_q1_goals INTEGER, home_q1_behinds INTEGER,",
          "home_q2_goals INTEGER, home_q2_behinds INTEGER,",
          "home_q3_goals INTEGER, home_q3_behinds INTEGER,",
          "home_q4_goals INTEGER, home_q4_behinds INTEGER,",
          "away_q1_goals INTEGER, away_q1_behinds INTEGER,",
          "away_q2_goals INTEGER, away_q2_behinds INTEGER,",
          "away_q3_goals INTEGER, away_q3_behinds INTEGER,",
          "away_q4_goals INTEGER, away_q4_behinds INTEGER",
        ].join(" "),
        player_match_stats: [
          "id INTEGER PRIMARY KEY, match_id INTEGER REFERENCES matches(id),",
          "player_id INTEGER REFERENCES players(id),",
          "team_id INTEGER REFERENCES teams(id),",
          "guernsey_number INTEGER, player_position TEXT,",
          "subbed TEXT, time_on_ground_pct REAL,",
          "kicks INTEGER, handballs INTEGER, disposals INTEGER,",
          "effective_disposals INTEGER, disposal_efficiency_pct REAL,",
          "marks INTEGER, bounces INTEGER, tackles INTEGER,",
          "one_percenters INTEGER, clangers INTEGER,",
          "contested_possessions INTEGER, uncontested_possessions INTEGER,",
          "goals INTEGER, behinds INTEGER, goal_assists INTEGER,",
          "shots_at_goal INTEGER, score_involvements INTEGER,",
          "score_launches INTEGER,",
          "centre_clearances INTEGER, stoppage_clearances INTEGER, clearances INTEGER,",
          "contested_marks INTEGER, marks_inside_fifty INTEGER,",
          "intercept_marks INTEGER, marks_on_lead INTEGER,",
          "free_kicks_for INTEGER, free_kicks_against INTEGER,",
          "hitouts INTEGER, hitouts_to_advantage INTEGER,",
          "hitout_win_pct REAL, ruck_contests INTEGER,",
          "inside_fifties INTEGER, rebounds INTEGER,",
          "turnovers INTEGER, intercepts INTEGER, metres_gained INTEGER,",
          "pressure_acts INTEGER, def_half_pressure_acts INTEGER,",
          "tackles_inside_fifty INTEGER, spoils INTEGER,",
          "contest_def_losses INTEGER, contest_def_one_on_ones INTEGER,",
          "contest_off_one_on_ones INTEGER, contest_off_wins INTEGER,",
          "effective_kicks INTEGER, ground_ball_gets INTEGER,",
          "f50_ground_ball_gets INTEGER,",
          "brownlow_votes INTEGER, rating_points REAL,",
          "afl_fantasy_score INTEGER, supercoach_score INTEGER,",
          "goal_accuracy REAL, goal_efficiency REAL, shot_efficiency REAL,",
          "kick_efficiency REAL, kick_to_handball_ratio REAL,",
          "contested_possession_rate REAL,",
          "contest_def_loss_pct REAL, contest_off_wins_pct REAL,",
          "centre_bounce_attendances INTEGER, kickins INTEGER,",
          "kickins_playon INTEGER, interchange_counts INTEGER,",
          "total_possessions INTEGER",
        ].join(" "),
        player_season_pav: [
          "id INTEGER PRIMARY KEY,",
          "player_id INTEGER REFERENCES players(id),",
          "season_id INTEGER REFERENCES seasons(id),",
          "team_id INTEGER REFERENCES teams(id),",
          "off_pav REAL, mid_pav REAL, def_pav REAL, total_pav REAL",
        ].join(" "),
        match_lineups: [
          "id INTEGER PRIMARY KEY,",
          "match_id INTEGER REFERENCES matches(id),",
          "player_id INTEGER REFERENCES players(id),",
          "team_id INTEGER REFERENCES teams(id),",
          "guernsey_number INTEGER, position TEXT,",
          "is_emergency INTEGER (0=no, 1=yes),",
          "is_substitute INTEGER (0=no, 1=yes)",
        ].join(" "),
      },
      notes: [
        "Players have no team_id column — a player's team is determined per-game via player_match_stats.team_id.",
        "player_season_pav is available 1998 onwards only. Use LEFT JOIN when combining with player_match_stats — pre-1998 seasons have stats but no PAV rows.",
        "total_pav = off_pav + mid_pav + def_pav.",
        "PAV zone meanings: off_pav = offensive (goals, score involvements, forward craft); mid_pav = midfield (disposals, clearances, tackles, contested ball); def_pav = defensive (intercepts, spoils, one-percenters, rebounds).",
        "PAV interpretation: 25+ exceptional (Brownlow contention), 20-25 great (All-Australian), 15-20 very good (team best-22), 10-15 solid contributor, 5-10 below average or limited games, <5 minimal contribution. Zone PAV of 10+ = All-Australian contention in that role.",
        "Opening Round has round_number = 0. It is played before Round 1 and must not be excluded from queries.",
        "round_type is either 'Regular' or 'Finals'. Use the round column for granular finals identification: QF, EF, SF, PF, GF.",
        "match date format is ISO 8601 (YYYY-MM-DD).",
        "Data covers AFL Men's competition from 1990 to the current season.",
        "Data comes from two sources: AFL API (current season, real-time) and fryzigg (historical, static). Some columns are only populated by one source.",
        "external_afl_player_id is the AFL API player ID (CD_I format), populated for ~1,535 players.",
        "metres_gained can be negative (valid — player lost net territory). Minimum observed: -92.",
        "abbreviation on teams is not populated.",
        "brownlow_votes: fryzigg source only. Available for historical matches (pre-2026). NULL for current 2026 season. Only ~3 non-zero values per match (votes go to best 3 players).",
        "supercoach_score: fryzigg source only. Available 2010-2019 only. NULL from 2020 onward (fryzigg stopped providing this data).",
        "afl_fantasy_score: available from both sources. Populated for most matches 2007+.",
        "subbed: fryzigg source only. Available for historical matches (pre-2026). NULL for current 2026 season. Values: 'Not Subbed', 'Subbed'.",
        "weather_temp_c and weather_type: fryzigg source only. Available ~2012-2025. NULL for pre-2012 and current 2026 season.",
        "local_time: Melbourne local time (AEST/AEDT) as HH:MM:SS. Available for all seasons.",
        "external_fryzigg_id: cross-reference ID from fryzigg source. Available for ~99% of historical matches.",
        "attendance: populated pre-2020 only (gap being addressed).",
        "Quarter scores (home_q1_goals through away_q4_behinds) are available for most matches 2000+ and enable quarter-by-quarter analysis.",
        "match_lineups contains announced team selections (before match day). Distinct from player_match_stats which records who actually played and their stats. A player can appear in lineups but not stats (emergency, late withdrawal).",
        "match_lineups is_emergency=1 means the player is named as an emergency and may not play. Only populated from 2024 onward — pre-2024 lineups have is_emergency=0 for all players.",
        "match_lineups is_substitute=1 marks all interchange/bench players (INT + SUB positions), not just the medical sub. To find just the medical substitute, filter on position = 'SUB'.",
        "match_lineups data is available from 2015 onward (AFL API source). No lineup data before 2015. Coverage is ~98-100% from 2020+; some Opening Round matches may be missing in 2024-2025.",
        "match_lineups position codes: 18 starting positions (FB, BPL, BPR, CHB, HBFL, HBFR, FF, FPL, FPR, CHF, HFFL, HFFR, C, WL, WR, R, RR, RK), plus INT (interchange), SUB (medical substitute), and EMERG (emergency, 2024+ only).",
        "match_lineups represent the post-change team — if an emergency replaces a late withdrawal, they appear as a starter, not as an emergency-who-played.",
        "round_type is either 'Regular' or 'Finals'. For granular finals identification use the round column: QF, EF, SF, PF, GF.",
        "Most players with both fryzigg and AFL API data are unified under a single player_id. A small number of common-name players (e.g., Mitch Brown, Andrew Phillips) may still have separate records for genuinely different people who share a name.",
      ],
      common_joins: {
        team_roster_pav: [
          "SELECT p.first_name, p.surname, psp.off_pav, psp.mid_pav, psp.def_pav, psp.total_pav",
          "FROM player_season_pav psp",
          "JOIN players p ON psp.player_id = p.id",
          "JOIN seasons s ON psp.season_id = s.id",
          "JOIN teams t ON psp.team_id = t.id",
          "WHERE t.name = ? AND s.year = ?",
          "ORDER BY psp.total_pav DESC",
        ].join("\n"),
        player_career_arc: [
          "SELECT s.year, SUM(pms.disposals) as total_disposals, SUM(pms.goals) as total_goals,",
          "  COUNT(*) as games, psp.total_pav, psp.off_pav, psp.mid_pav, psp.def_pav",
          "FROM player_match_stats pms",
          "JOIN matches m ON pms.match_id = m.id",
          "JOIN seasons s ON m.season_id = s.id",
          "LEFT JOIN player_season_pav psp ON psp.player_id = pms.player_id AND psp.season_id = s.id",
          "WHERE pms.player_id = ?",
          "GROUP BY s.year, psp.total_pav, psp.off_pav, psp.mid_pav, psp.def_pav",
          "ORDER BY s.year",
        ].join("\n"),
        zone_leaders: [
          "SELECT p.first_name, p.surname, t.name as team, psp.mid_pav, psp.off_pav, psp.def_pav, psp.total_pav",
          "FROM player_season_pav psp",
          "JOIN players p ON psp.player_id = p.id",
          "JOIN seasons s ON psp.season_id = s.id",
          "JOIN teams t ON psp.team_id = t.id",
          "WHERE s.year = ?",
          "ORDER BY psp.total_pav DESC",
          "LIMIT 20",
        ].join("\n"),
        match_with_teams_venue: [
          "SELECT m.date, m.round, ht.name as home_team, at.name as away_team,",
          "  m.home_points, m.away_points, m.margin, v.name as venue",
          "FROM matches m",
          "JOIN teams ht ON m.home_team_id = ht.id",
          "JOIN teams at ON m.away_team_id = at.id",
          "JOIN venues v ON m.venue_id = v.id",
          "WHERE m.season_id = (SELECT id FROM seasons WHERE year = ?)",
        ].join("\n"),
        lineup_round_comparison: [
          "-- Compare team lineups between two rounds (shows ins/outs)",
          "SELECT 'IN' as change, p.first_name, p.surname, ml.position",
          "FROM match_lineups ml",
          "JOIN matches m ON ml.match_id = m.id",
          "JOIN players p ON ml.player_id = p.id",
          "JOIN teams t ON ml.team_id = t.id",
          "WHERE t.name = ? AND m.round_number = ? AND ml.is_emergency = 0",
          "  AND ml.player_id NOT IN (",
          "    SELECT ml2.player_id FROM match_lineups ml2",
          "    JOIN matches m2 ON ml2.match_id = m2.id",
          "    WHERE ml2.team_id = ml.team_id AND m2.round_number = ? AND m2.season_id = m.season_id AND ml2.is_emergency = 0",
          "  )",
          "UNION ALL",
          "SELECT 'OUT', p.first_name, p.surname, ml.position",
          "FROM match_lineups ml",
          "JOIN matches m ON ml.match_id = m.id",
          "JOIN players p ON ml.player_id = p.id",
          "JOIN teams t ON ml.team_id = t.id",
          "WHERE t.name = ? AND m.round_number = ? AND ml.is_emergency = 0",
          "  AND ml.player_id NOT IN (",
          "    SELECT ml2.player_id FROM match_lineups ml2",
          "    JOIN matches m2 ON ml2.match_id = m2.id",
          "    WHERE ml2.team_id = ml.team_id AND m2.round_number = ? AND m2.season_id = m.season_id AND ml2.is_emergency = 0",
          "  )",
        ].join("\n"),
        lineup_with_pav: [
          "-- Team lineup enriched with PAV data",
          "SELECT p.first_name, p.surname, ml.position, ml.guernsey_number,",
          "  ml.is_emergency, ml.is_substitute,",
          "  psp.off_pav, psp.mid_pav, psp.def_pav, psp.total_pav",
          "FROM match_lineups ml",
          "JOIN matches m ON ml.match_id = m.id",
          "JOIN players p ON ml.player_id = p.id",
          "JOIN teams t ON ml.team_id = t.id",
          "JOIN seasons s ON m.season_id = s.id",
          "LEFT JOIN player_season_pav psp ON psp.player_id = p.id AND psp.season_id = s.id",
          "WHERE t.name = ? AND m.round_number = ? AND s.year = ?",
          "ORDER BY ml.is_emergency, psp.total_pav DESC NULLS LAST",
        ].join("\n"),
        ladder: [
          "-- AFL Ladder for a season (regular season only)",
          "SELECT t.name AS team,",
          "  COUNT(*) AS played,",
          "  SUM(CASE WHEN (m.home_team_id = t.id AND m.home_points > m.away_points) OR (m.away_team_id = t.id AND m.away_points > m.home_points) THEN 1 ELSE 0 END) AS wins,",
          "  SUM(CASE WHEN (m.home_team_id = t.id AND m.home_points < m.away_points) OR (m.away_team_id = t.id AND m.away_points < m.home_points) THEN 1 ELSE 0 END) AS losses,",
          "  SUM(CASE WHEN m.home_points = m.away_points THEN 1 ELSE 0 END) AS draws,",
          "  SUM(CASE WHEN m.home_team_id = t.id THEN m.home_points ELSE m.away_points END) AS points_for,",
          "  SUM(CASE WHEN m.home_team_id = t.id THEN m.away_points ELSE m.home_points END) AS points_against,",
          "  ROUND(100.0 * SUM(CASE WHEN m.home_team_id = t.id THEN m.home_points ELSE m.away_points END) / NULLIF(SUM(CASE WHEN m.home_team_id = t.id THEN m.away_points ELSE m.home_points END), 0), 1) AS percentage,",
          "  SUM(CASE WHEN (m.home_team_id = t.id AND m.home_points > m.away_points) OR (m.away_team_id = t.id AND m.away_points > m.home_points) THEN 4 WHEN m.home_points = m.away_points THEN 2 ELSE 0 END) AS premiership_points",
          "FROM teams t",
          "JOIN matches m ON t.id = m.home_team_id OR t.id = m.away_team_id",
          "JOIN seasons s ON m.season_id = s.id",
          "WHERE s.year = ? AND m.round_type = 'Regular' AND m.home_points IS NOT NULL",
          "GROUP BY t.id",
          "ORDER BY premiership_points DESC, percentage DESC",
        ].join("\n"),
      },
    },
    query_api: {
      usage:
        "db.prepare(sql).bind(param1, param2, ...).all() returns { results: Row[] }. Use .first() for a single row.",
      methods: [
        "db.prepare(sql).bind(...args).all() — returns { results: Row[], success: boolean }",
        "db.prepare(sql).bind(...args).first() — returns first Row or null",
      ],
      notes:
        "Read-only. 30-second timeout. Use ? for parameter binding. The db object is available in the sandbox via an RPC proxy that transparently handles D1 calls.",
    },
  };
}
