export function getSchemaInfo() {
  return {
    database: {
      engine: "SQLite (Cloudflare D1)",
      competitions: {
        AFLM: {
          name: "AFL Men's",
          years: "1990 to current season",
          coverage: { matches: true, stats: true, lineups: "2015+", pav: "1998+" },
        },
        AFLW: {
          name: "AFL Women's",
          years: "2017 to current season",
          coverage: { matches: true, stats: true, lineups: "2017+", pav: "2017+" },
        },
        VFL: {
          name: "Victorian Football League",
          years: "2021 to current season",
          coverage: { matches: true, stats: true, lineups: "best-effort", pav: false },
        },
        VFLW: {
          name: "VFL Women's",
          years: "2021 to current season",
          coverage: { matches: true, stats: true, lineups: "best-effort", pav: false },
        },
      },
      tables: {
        competitions: "id INTEGER PRIMARY KEY, code TEXT (AFLM/AFLW/VFL/VFLW), name TEXT",
        seasons:
          "id INTEGER PRIMARY KEY, competition_id INTEGER REFERENCES competitions(id), year INTEGER, is_complete INTEGER (0=in-progress, 1=all matches played)",
        teams:
          "id INTEGER PRIMARY KEY, name TEXT, abbreviation TEXT, competition_id INTEGER REFERENCES competitions(id)",
        venues: "id INTEGER PRIMARY KEY, name TEXT",
        players: [
          "id INTEGER PRIMARY KEY, first_name TEXT, surname TEXT, external_id TEXT,",
          "external_afl_player_id TEXT,",
          "date_of_birth TEXT, height_cm INTEGER, weight_kg INTEGER, is_retired INTEGER",
        ].join(" "),
        matches: [
          "id INTEGER PRIMARY KEY, season_id INTEGER REFERENCES seasons(id),",
          "round TEXT, round_abbreviation TEXT, round_number INTEGER, round_type TEXT,",
          "date TEXT, local_time TEXT,",
          "venue_id INTEGER REFERENCES venues(id),",
          "home_team_id INTEGER REFERENCES teams(id),",
          "away_team_id INTEGER REFERENCES teams(id),",
          "home_goals INTEGER, home_behinds INTEGER, home_points INTEGER,",
          "away_goals INTEGER, away_behinds INTEGER, away_points INTEGER,",
          "margin INTEGER, attendance INTEGER,",
          "weather_temp_c REAL, weather_type TEXT,",
          "external_afltables_id TEXT, external_fryzigg_id TEXT,",
          "external_afl_id TEXT,",
          "home_rushed_behinds INTEGER, away_rushed_behinds INTEGER,",
          "home_minutes_in_front INTEGER, away_minutes_in_front INTEGER,",
          "home_q1_goals INTEGER, home_q1_behinds INTEGER,",
          "home_q2_goals INTEGER, home_q2_behinds INTEGER,",
          "home_q3_goals INTEGER, home_q3_behinds INTEGER,",
          "home_q4_goals INTEGER, home_q4_behinds INTEGER,",
          "away_q1_goals INTEGER, away_q1_behinds INTEGER,",
          "away_q2_goals INTEGER, away_q2_behinds INTEGER,",
          "away_q3_goals INTEGER, away_q3_behinds INTEGER,",
          "away_q4_goals INTEGER, away_q4_behinds INTEGER,",
          "status TEXT, live_period_status TEXT",
        ].join(" "),
        player_match_stats: [
          "id INTEGER PRIMARY KEY, match_id INTEGER REFERENCES matches(id),",
          "player_id INTEGER REFERENCES players(id),",
          "team_id INTEGER REFERENCES teams(id),",
          "guernsey_number INTEGER, player_position TEXT,",
          "subbed TEXT, time_on_ground_pct REAL,",
          "kicks INTEGER, handballs INTEGER, disposals INTEGER,",
          "effective_disposals INTEGER, disposal_efficiency_pct REAL,",
          "marks INTEGER, bounces INTEGER, tackles INTEGER,",
          "one_percenters INTEGER, clangers INTEGER,",
          "contested_possessions INTEGER, uncontested_possessions INTEGER,",
          "goals INTEGER, behinds INTEGER, goal_assists INTEGER,",
          "shots_at_goal INTEGER, score_involvements INTEGER,",
          "score_launches INTEGER,",
          "centre_clearances INTEGER, stoppage_clearances INTEGER, clearances INTEGER,",
          "contested_marks INTEGER, marks_inside_fifty INTEGER,",
          "intercept_marks INTEGER, marks_on_lead INTEGER,",
          "free_kicks_for INTEGER, free_kicks_against INTEGER,",
          "hitouts INTEGER, hitouts_to_advantage INTEGER,",
          "hitout_win_pct REAL, ruck_contests INTEGER,",
          "inside_fifties INTEGER, rebounds INTEGER,",
          "turnovers INTEGER, intercepts INTEGER, metres_gained INTEGER,",
          "pressure_acts INTEGER, def_half_pressure_acts INTEGER,",
          "tackles_inside_fifty INTEGER, spoils INTEGER,",
          "contest_def_losses INTEGER, contest_def_one_on_ones INTEGER,",
          "contest_off_one_on_ones INTEGER, contest_off_wins INTEGER,",
          "effective_kicks INTEGER, ground_ball_gets INTEGER,",
          "f50_ground_ball_gets INTEGER,",
          "brownlow_votes INTEGER, rating_points REAL,",
          "afl_fantasy_score INTEGER, supercoach_score INTEGER,",
          "goal_accuracy REAL, goal_efficiency REAL, shot_efficiency REAL,",
          "kick_efficiency REAL, kick_to_handball_ratio REAL,",
          "contested_possession_rate REAL,",
          "contest_def_loss_pct REAL, contest_off_wins_pct REAL,",
          "centre_bounce_attendances INTEGER, kickins INTEGER,",
          "kickins_playon INTEGER, interchange_counts INTEGER,",
          "total_possessions INTEGER",
        ].join(" "),
        player_season_pav: [
          "id INTEGER PRIMARY KEY,",
          "player_id INTEGER REFERENCES players(id),",
          "season_id INTEGER REFERENCES seasons(id),",
          "team_id INTEGER REFERENCES teams(id),",
          "off_pav REAL, mid_pav REAL, def_pav REAL, total_pav REAL",
        ].join(" "),
        match_lineups: [
          "id INTEGER PRIMARY KEY,",
          "match_id INTEGER REFERENCES matches(id),",
          "player_id INTEGER REFERENCES players(id),",
          "team_id INTEGER REFERENCES teams(id),",
          "guernsey_number INTEGER, position TEXT,",
          "is_emergency INTEGER (0=no, 1=yes),",
          "is_substitute INTEGER (0=no, 1=yes)",
        ].join(" "),
      },
      notes: [
        // Multi-competition rules — read first
        "ALWAYS filter queries by competition. Join `seasons s ON m.season_id = s.id` then `competitions c ON s.competition_id = c.id` and add `WHERE c.code = ?`. Without this filter, results mix competitions silently — team rows with the same name (e.g. Carlton AFLM vs Carlton VFL) have distinct team_id values, so unfiltered aggregates double-count.",
        "Available competitions: AFLM (1990+), AFLW (2017+), VFL (2021+), VFLW (2021+). See the `competitions` block at the top of this schema for per-competition coverage of matches, stats, lineups, and PAV.",
        "PAV is computed for AFLM (1998+) and AFLW (2017+) only. VFL/VFLW have no PAV rows because the AFL API does not populate the required inputs (`goal_assists`, `marks_inside_fifty`, `one_percenters` are all NULL upstream for those competitions).",
        // Round labels — competition-specific
        "Round labels: matches has TWO round-string columns mirroring the AFL API directly (same approach as the R fitzRoy package — no cross-competition normalisation):",
        "- `round` is the long form: `Round 1`–`Round N`, `Opening Round` (AFLM 2024+, round_number=0), `Wildcard` (VFL only, before finals), and finals `Finals Week 1` / `Semi Finals` / `Preliminary Finals` / `Grand Final`.",
        "- `round_abbreviation` is the AFL's short form: `Rd 1`–`Rd N`, `OR`, `WC`, `FW1`, `SF`, `PF`, `GF`. Stable across all four competitions; useful for compact display and abbreviation-based filters.",
        "- `round_number` is a per-season ordinal: continuous through regular and finals (e.g. AFLM 2024 finals are 25–28; AFLW 2025 finals are 13–16; VFL 2025 has Wildcard at 22 then finals 23–26). Round numbers don't align across competitions — AFLM R1 is March, AFLW R1 is August, VFL R1 is April.",
        "- `round_type` is `Regular` (home-and-away + Opening Round + Wildcard) or `Finals`.",
        "Pre-v3.0.0 historical data may still have legacy `EF`/`QF`/`SF`/`PF`/`GF` strings in `round` for AFLM finals 2012–2025; these get rewritten to the long form on the next backfill.",
        "round_type is either 'Regular' or 'Finals'. For granular finals identification use the round column.",
        "Opening Round (round_number=0, only present for AFLM 2024+) is played before Round 1 and must not be excluded from queries.",
        "AFLM 2012–2025 finals labels were rewritten in v3.0.0 to match fitzroy v2.1's labels; legacy `EF/QF/SF/PF/GF` no longer appears in the data.",
        // Players + teams
        "Players have no team_id column — a player's team is determined per-game via player_match_stats.team_id. The same player_id can appear in multiple competitions in the same season (e.g. an AFLM-listed reserves player who also plays VFL games for the affiliate); resolve their competition per stat row via match → season → competition.",
        // PAV semantics
        "total_pav ≈ off_pav + mid_pav + def_pav. ~12-15% of rows differ by exactly ±0.01 because each component is rounded independently. Treat the relationship as approximate, not exact.",
        "PAV zone meanings: off_pav = offensive (goals, score involvements, forward craft); mid_pav = midfield (disposals, clearances, tackles, contested ball); def_pav = defensive (intercepts, spoils, one-percenters, rebounds).",
        "PAV interpretation (AFLM scale): 25+ exceptional (Brownlow contention), 20-25 great (All-Australian), 15-20 very good (team best-22), 10-15 solid contributor, 5-10 below average or limited games, <5 minimal contribution. AFLW PAV is on a similar but lower-totals scale because of shorter games and smaller squads.",
        "player_season_pav uses LEFT JOIN when combining with player_match_stats — pre-1998 AFLM, pre-2017 AFLW, and any VFL/VFLW row will have no PAV.",
        // Format
        "match date format is ISO 8601 (YYYY-MM-DD).",
        "matches.margin is signed from the home team's perspective: positive = home team won by that many points, negative = away team won. Use ABS(margin) for absolute margin.",
        "teams.abbreviation: AFL standard 2–4 letter codes for AFLM (ADE, BL, CARL, COLL, ESS, FITZ, FREO, GEEL, GCFC, GWS, HAW, MELB, NM, PORT, RICH, STK, SYD, WCE, WB). May be NULL for AFLW/VFL/VFLW teams sourced from fitzroy.",
        // Source-specific column coverage (AFLM-focused; VFL/VFLW use afl-api only)
        "Data sources: all four competitions ingest current data from the AFL API. AFLM also has historical (pre-2012) data backfilled from fryzigg, which populates a few columns AFL API doesn't (subbed, weather_*, supercoach_score for 2007–2019). AFLW comes from AFL API only. VFL/VFLW come from AFL API only.",
        "external_afl_player_id is the AFL API player ID (CD_I format), populated for AFL API-sourced rows.",
        "metres_gained can be negative (valid — player lost net territory). Minimum observed: -92.",
        "brownlow_votes: AFLM only (the Brownlow Medal is an AFL Men's award). Complete from 1990-2025 except for 22 regular-season matches across 2022-2025 with partial vote totals; NULL for the current 2026 AFLM season and for all AFLW/VFL/VFLW rows.",
        "supercoach_score: AFLM only, fryzigg source. Fully populated 2007-2019. NULL pre-2007, from 2020 onward, and for AFLW/VFL/VFLW.",
        "afl_fantasy_score: AFLM via both sources from 2007 onward (6 NULLs in 2020). Sparse or NULL elsewhere.",
        "subbed: AFLM-only fryzigg source. Populated 1990-2019. Values: 'Not Subbed', 'Subbed'.",
        "weather_temp_c and weather_type: AFLM-only fryzigg source. Populated 2010-2025. NULL elsewhere.",
        "local_time: Melbourne local time (AEST/AEDT) as HH:MM:SS. Available for all seasons across all competitions.",
        "external_fryzigg_id: AFLM cross-reference ID from fryzigg. ~99% of AFLM historical matches.",
        "attendance: AFLM only, populated pre-2020. NULL elsewhere.",
        "Quarter scores (home_q1_goals through away_q4_behinds): AFLM populated for all matches from 2020 onward; NULL for AFLM 1990-2019. AFLW/VFL/VFLW: populated where AFL API provides them, NULL otherwise.",
        "matches.status is the match lifecycle. Values: 'Upcoming', 'Live', 'Complete', 'Postponed', 'Cancelled'. Populated from 2026-06 onward for any match the AFL API sync touches; NULL on historical rows backfilled before that date and on rows from non-afl-api sources (fryzigg / afl-tables historical imports).",
        "matches.live_period_status is the raw AFL API score-level status, intended for live-match siren detection (quarter-time / half-time / full-time). Observed values: 'LIVE', 'QTR_TIME', 'HALF_TIME', '3QTR_TIME', 'FULL_TIME'. Values are upstream-defined raw strings and may change without notice — treat as opaque text. NULL pre-match, for completed historical rows, and for any match outside the AFL API source.",
        // Lineups
        "match_lineups represents the post-change team — the players who actually took the field. AFLM 2023+ from AFL API post-change feed; AFLM 2021–2022 derived from player_match_stats (Thursday-night announced team is all the API returns). AFLW: AFL API direct. VFL/VFLW: best-effort — fitzroy may return empty for some rounds; treat absence as not-yet-published rather than canonical.",
        "match_lineups is_emergency=1 means the player is named as an emergency and may not play. Only populated from AFLM 2024 onward — pre-2024 AFLM and other competitions have is_emergency=0 for all players.",
        "match_lineups is_substitute=1 marks all interchange/bench players (INT + SUB positions), not just the medical sub. To find just the medical substitute, filter on position = 'SUB'.",
        "match_lineups data is available from 2015 onward (AFLM via AFL API). AFLW from 2017+. Four specific AFLM rounds have no lineup rows because fitzroy's afl-api source rejects them: 2015 R4, 2017 R8, 2018 R9, 2019 R11, plus the 2015 GF.",
        "match_lineups position codes: 18 starting positions (FB, BPL, BPR, CHB, HBFL, HBFR, FF, FPL, FPR, CHF, HFFL, HFFR, C, WL, WR, R, RR, RK), plus INT (interchange), SUB (medical substitute), and EMERG (emergency, AFLM 2024+ only).",
        "Most players with both fryzigg and AFL API data are unified under a single player_id. A small number of common-name players may have separate records for genuinely different people who share a name.",
        "Integrity-check views (v_integrity_disposals, v_integrity_match_points, v_integrity_quarter_scores, v_integrity_margin, v_integrity_brownlow) return one row per invariant violation; an empty result set means the invariant holds.",
        "seasons.is_complete: 1 when every match in the season has been played (home_points NOT NULL for all rows). 0 for in-progress and not-started seasons.",
      ],
      column_coverage: {
        description:
          "First/last fully populated season for AFLM-specific columns whose coverage doesn't span the whole AFLM dataset. Most are NULL or sparse for AFLW/VFL/VFLW — when in doubt, sample. Columns not listed here are populated for all seasons within each competition's coverage window.",
        columns: {
          "matches.attendance": {
            from: 1990,
            to: 2019,
            notes: "AFLM only. NULL from 2020 onward and for non-AFLM competitions.",
          },
          "matches.weather_temp_c": {
            from: 2010,
            to: 2025,
            notes: "AFLM only (fryzigg source). NULL elsewhere.",
          },
          "matches.weather_type": {
            from: 2010,
            to: 2025,
            notes: "AFLM only (fryzigg source). Same coverage as weather_temp_c.",
          },
          "matches.home_q1_goals_through_away_q4_behinds": {
            from: 2020,
            to: "current",
            notes:
              "AFLM 2020+ complete. Other competitions: where AFL API provides them, otherwise NULL.",
          },
          "player_match_stats.brownlow_votes": {
            from: 1990,
            to: 2025,
            notes:
              "AFLM only (Brownlow is an AFL Men's award). NULL for AFLW/VFL/VFLW rows and the current 2026 AFLM season.",
          },
          "player_match_stats.supercoach_score": {
            from: 2007,
            to: 2019,
            notes: "AFLM only (fryzigg). NULL pre-2007, from 2020 onward, and elsewhere.",
          },
          "player_match_stats.afl_fantasy_score": {
            from: 2007,
            to: "current",
            notes: "AFLM 2007+. Sparse for other competitions.",
          },
          "player_match_stats.subbed": {
            from: 1990,
            to: 2019,
            notes: "AFLM only (fryzigg).",
          },
          "player_match_stats.disposal_efficiency_pct": {
            from: 2012,
            to: "current",
            notes: "AFLM 2012+. Available for AFLW from 2017+ and VFL/VFLW from 2021+.",
          },
          "player_match_stats.score_involvements": {
            from: 2015,
            to: "current",
            notes: "AFLM 2015+ complete. AFLW from 2017. Sparse for VFL/VFLW.",
          },
          "player_match_stats.metres_gained": {
            from: 2015,
            to: "current",
            notes: "AFLM 2015+. NULL for VFL/VFLW.",
          },
          "player_match_stats.intercepts": {
            from: 2015,
            to: "current",
            notes: "AFLM 2015+. AFLW 2017+. VFL/VFLW: present where AFL API tracks it.",
          },
          "player_match_stats.pressure_acts": {
            from: 2017,
            to: "current",
            notes: "AFLM 2017+. NULL for VFL/VFLW.",
          },
          "player_match_stats.goal_assists": {
            from: 1990,
            to: "current",
            notes:
              "AFLM 1990+ and AFLW 2017+. NULL for ALL VFL and VFLW rows (AFL API does not populate this for those competitions).",
          },
          "player_match_stats.marks_inside_fifty": {
            from: 1990,
            to: "current",
            notes:
              "AFLM 1990+ and AFLW 2017+. NULL for ALL VFL and VFLW rows (AFL API does not populate this for those competitions).",
          },
          "player_match_stats.one_percenters": {
            from: 1990,
            to: "current",
            notes:
              "AFLM 1990+ and AFLW 2017+. NULL for ALL VFL and VFLW rows (AFL API does not populate this for those competitions).",
          },
          "player_season_pav.*": {
            from: 1998,
            to: "current",
            notes:
              "AFLM 1998+ and AFLW 2017+. No PAV rows for VFL/VFLW. Use LEFT JOIN when combining with player_match_stats.",
          },
        },
      },
      common_joins: {
        // Always filter by competition — first bound parameter in every example.
        multi_comp_summary: [
          "-- Per-competition match counts for a season",
          "SELECT c.code AS competition, COUNT(m.id) AS matches",
          "FROM competitions c",
          "JOIN seasons s ON s.competition_id = c.id",
          "JOIN matches m ON m.season_id = s.id",
          "WHERE s.year = ?",
          "GROUP BY c.code",
          "ORDER BY c.code",
        ].join("\n"),
        team_roster_pav: [
          "-- Bind: competition, team name, season year",
          "SELECT p.first_name, p.surname, psp.off_pav, psp.mid_pav, psp.def_pav, psp.total_pav",
          "FROM player_season_pav psp",
          "JOIN players p ON psp.player_id = p.id",
          "JOIN seasons s ON psp.season_id = s.id",
          "JOIN competitions c ON s.competition_id = c.id",
          "JOIN teams t ON psp.team_id = t.id",
          "WHERE c.code = ? AND t.name = ? AND s.year = ?",
          "ORDER BY psp.total_pav DESC",
        ].join("\n"),
        player_career_arc: [
          "-- Bind: competition, player_id",
          "SELECT s.year, SUM(pms.disposals) as total_disposals, SUM(pms.goals) as total_goals,",
          "  COUNT(*) as games, psp.total_pav, psp.off_pav, psp.mid_pav, psp.def_pav",
          "FROM player_match_stats pms",
          "JOIN matches m ON pms.match_id = m.id",
          "JOIN seasons s ON m.season_id = s.id",
          "JOIN competitions c ON s.competition_id = c.id",
          "LEFT JOIN player_season_pav psp ON psp.player_id = pms.player_id AND psp.season_id = s.id",
          "WHERE c.code = ? AND pms.player_id = ?",
          "GROUP BY s.year, psp.total_pav, psp.off_pav, psp.mid_pav, psp.def_pav",
          "ORDER BY s.year",
        ].join("\n"),
        zone_leaders: [
          "-- Bind: competition, season year",
          "SELECT p.first_name, p.surname, t.name as team, psp.mid_pav, psp.off_pav, psp.def_pav, psp.total_pav",
          "FROM player_season_pav psp",
          "JOIN players p ON psp.player_id = p.id",
          "JOIN seasons s ON psp.season_id = s.id",
          "JOIN competitions c ON s.competition_id = c.id",
          "JOIN teams t ON psp.team_id = t.id",
          "WHERE c.code = ? AND s.year = ?",
          "ORDER BY psp.total_pav DESC",
          "LIMIT 20",
        ].join("\n"),
        match_with_teams_venue: [
          "-- Bind: competition, season year",
          "SELECT m.date, m.round, ht.name as home_team, at.name as away_team,",
          "  m.home_points, m.away_points, m.margin, v.name as venue",
          "FROM matches m",
          "JOIN seasons s ON m.season_id = s.id",
          "JOIN competitions c ON s.competition_id = c.id",
          "JOIN teams ht ON m.home_team_id = ht.id",
          "JOIN teams at ON m.away_team_id = at.id",
          "JOIN venues v ON m.venue_id = v.id",
          "WHERE c.code = ? AND s.year = ?",
        ].join("\n"),
        lineup_round_comparison: [
          "-- Compare team lineups between two rounds (shows ins/outs)",
          "-- Bind: competition, team name, current round number, prev round number, then again for OUT half",
          "SELECT 'IN' as change, p.first_name, p.surname, ml.position",
          "FROM match_lineups ml",
          "JOIN matches m ON ml.match_id = m.id",
          "JOIN seasons s ON m.season_id = s.id",
          "JOIN competitions c ON s.competition_id = c.id",
          "JOIN players p ON ml.player_id = p.id",
          "JOIN teams t ON ml.team_id = t.id",
          "WHERE c.code = ? AND t.name = ? AND m.round_number = ? AND ml.is_emergency = 0",
          "  AND ml.player_id NOT IN (",
          "    SELECT ml2.player_id FROM match_lineups ml2",
          "    JOIN matches m2 ON ml2.match_id = m2.id",
          "    WHERE ml2.team_id = ml.team_id AND m2.round_number = ? AND m2.season_id = m.season_id AND ml2.is_emergency = 0",
          "  )",
          "UNION ALL",
          "SELECT 'OUT', p.first_name, p.surname, ml.position",
          "FROM match_lineups ml",
          "JOIN matches m ON ml.match_id = m.id",
          "JOIN seasons s ON m.season_id = s.id",
          "JOIN competitions c ON s.competition_id = c.id",
          "JOIN players p ON ml.player_id = p.id",
          "JOIN teams t ON ml.team_id = t.id",
          "WHERE c.code = ? AND t.name = ? AND m.round_number = ? AND ml.is_emergency = 0",
          "  AND ml.player_id NOT IN (",
          "    SELECT ml2.player_id FROM match_lineups ml2",
          "    JOIN matches m2 ON ml2.match_id = m2.id",
          "    WHERE ml2.team_id = ml.team_id AND m2.round_number = ? AND m2.season_id = m.season_id AND ml2.is_emergency = 0",
          "  )",
        ].join("\n"),
        lineup_with_pav: [
          "-- Team lineup enriched with PAV data",
          "-- Bind: competition, team name, round number, season year",
          "SELECT p.first_name, p.surname, ml.position, ml.guernsey_number,",
          "  ml.is_emergency, ml.is_substitute,",
          "  psp.off_pav, psp.mid_pav, psp.def_pav, psp.total_pav",
          "FROM match_lineups ml",
          "JOIN matches m ON ml.match_id = m.id",
          "JOIN seasons s ON m.season_id = s.id",
          "JOIN competitions c ON s.competition_id = c.id",
          "JOIN players p ON ml.player_id = p.id",
          "JOIN teams t ON ml.team_id = t.id",
          "LEFT JOIN player_season_pav psp ON psp.player_id = p.id AND psp.season_id = s.id",
          "WHERE c.code = ? AND t.name = ? AND m.round_number = ? AND s.year = ?",
          "ORDER BY ml.is_emergency, psp.total_pav DESC NULLS LAST",
        ].join("\n"),
        ladder: [
          "-- Ladder for a season (regular season only). Works for any competition.",
          "-- Bind: competition, season year",
          "SELECT t.name AS team,",
          "  COUNT(*) AS played,",
          "  SUM(CASE WHEN (m.home_team_id = t.id AND m.home_points > m.away_points) OR (m.away_team_id = t.id AND m.away_points > m.home_points) THEN 1 ELSE 0 END) AS wins,",
          "  SUM(CASE WHEN (m.home_team_id = t.id AND m.home_points < m.away_points) OR (m.away_team_id = t.id AND m.away_points < m.home_points) THEN 1 ELSE 0 END) AS losses,",
          "  SUM(CASE WHEN m.home_points = m.away_points THEN 1 ELSE 0 END) AS draws,",
          "  SUM(CASE WHEN m.home_team_id = t.id THEN m.home_points ELSE m.away_points END) AS points_for,",
          "  SUM(CASE WHEN m.home_team_id = t.id THEN m.away_points ELSE m.home_points END) AS points_against,",
          "  ROUND(100.0 * SUM(CASE WHEN m.home_team_id = t.id THEN m.home_points ELSE m.away_points END) / NULLIF(SUM(CASE WHEN m.home_team_id = t.id THEN m.away_points ELSE m.home_points END), 0), 1) AS percentage,",
          "  SUM(CASE WHEN (m.home_team_id = t.id AND m.home_points > m.away_points) OR (m.away_team_id = t.id AND m.away_points > m.home_points) THEN 4 WHEN m.home_points = m.away_points THEN 2 ELSE 0 END) AS premiership_points",
          "FROM teams t",
          "JOIN competitions c ON t.competition_id = c.id",
          "JOIN matches m ON t.id = m.home_team_id OR t.id = m.away_team_id",
          "JOIN seasons s ON m.season_id = s.id",
          "WHERE c.code = ? AND s.year = ? AND m.round_type = 'Regular' AND m.home_points IS NOT NULL",
          "GROUP BY t.id",
          "ORDER BY premiership_points DESC, percentage DESC",
        ].join("\n"),
      },
    },
    query_api: {
      usage:
        "db.prepare(sql).bind(param1, param2, ...).all() returns { results: Row[] }. Use .first() for a single row.",
      methods: [
        "db.prepare(sql).bind(...args).all() — returns { results: Row[], success: boolean }",
        "db.prepare(sql).bind(...args).first() — returns first Row or null",
      ],
      notes:
        "Read-only. 30-second timeout. Use ? for parameter binding. The db object is available in the sandbox via an RPC proxy that transparently handles D1 calls. Always filter your queries by competition (see notes above).",
    },
  };
}
