export function getSchemaInfo() {
  return {
    database: {
      engine: "SQLite (Cloudflare D1)",
      tables: {
        competitions: "id INTEGER PRIMARY KEY, code TEXT, name TEXT",
        seasons: "id INTEGER PRIMARY KEY, competition_id INTEGER REFERENCES competitions(id), year INTEGER",
        teams: "id INTEGER PRIMARY KEY, name TEXT, abbreviation TEXT, competition_id INTEGER REFERENCES competitions(id)",
        venues: "id INTEGER PRIMARY KEY, name TEXT",
        players: [
          "id INTEGER PRIMARY KEY, first_name TEXT, surname TEXT, external_id TEXT,",
          "date_of_birth TEXT, height_cm REAL, weight_kg REAL, is_retired INTEGER",
        ].join(" "),
        matches: [
          "id INTEGER PRIMARY KEY, season_id INTEGER REFERENCES seasons(id),",
          "round TEXT, round_number INTEGER, round_type TEXT,",
          "date TEXT, local_time TEXT,",
          "venue_id INTEGER REFERENCES venues(id),",
          "home_team_id INTEGER REFERENCES teams(id),",
          "away_team_id INTEGER REFERENCES teams(id),",
          "home_goals INTEGER, home_behinds INTEGER, home_points INTEGER,",
          "away_goals INTEGER, away_behinds INTEGER, away_points INTEGER,",
          "margin INTEGER, attendance INTEGER,",
          "weather_temp_c REAL, weather_type TEXT,",
          "external_afltables_id TEXT, external_fryzigg_id TEXT",
        ].join(" "),
        player_match_stats: [
          "id INTEGER PRIMARY KEY, match_id INTEGER REFERENCES matches(id),",
          "player_id INTEGER REFERENCES players(id),",
          "team_id INTEGER REFERENCES teams(id),",
          "guernsey_number INTEGER, player_position TEXT,",
          "subbed TEXT, time_on_ground_pct REAL,",
          "kicks INTEGER, handballs INTEGER, disposals INTEGER,",
          "effective_disposals INTEGER, disposal_efficiency_pct REAL,",
          "marks INTEGER, bounces INTEGER, tackles INTEGER,",
          "one_percenters INTEGER, clangers INTEGER,",
          "contested_possessions INTEGER, uncontested_possessions INTEGER,",
          "goals INTEGER, behinds INTEGER, goal_assists INTEGER,",
          "shots_at_goal INTEGER, score_involvements INTEGER,",
          "score_launches INTEGER,",
          "centre_clearances INTEGER, stoppage_clearances INTEGER, clearances INTEGER,",
          "contested_marks INTEGER, marks_inside_fifty INTEGER,",
          "intercept_marks INTEGER, marks_on_lead INTEGER,",
          "free_kicks_for INTEGER, free_kicks_against INTEGER,",
          "hitouts INTEGER, hitouts_to_advantage INTEGER,",
          "hitout_win_pct REAL, ruck_contests INTEGER,",
          "inside_fifties INTEGER, rebounds INTEGER,",
          "turnovers INTEGER, intercepts INTEGER, metres_gained INTEGER,",
          "pressure_acts INTEGER, def_half_pressure_acts INTEGER,",
          "tackles_inside_fifty INTEGER, spoils INTEGER,",
          "contest_def_losses INTEGER, contest_def_one_on_ones INTEGER,",
          "contest_off_one_on_ones INTEGER, contest_off_wins INTEGER,",
          "effective_kicks INTEGER, ground_ball_gets INTEGER,",
          "f50_ground_ball_gets INTEGER,",
          "brownlow_votes INTEGER, rating_points REAL,",
          "afl_fantasy_score INTEGER, supercoach_score INTEGER",
        ].join(" "),
        player_season_pav: [
          "id INTEGER PRIMARY KEY,",
          "player_id INTEGER REFERENCES players(id),",
          "season_id INTEGER REFERENCES seasons(id),",
          "team_id INTEGER REFERENCES teams(id),",
          "off_pav REAL, mid_pav REAL, def_pav REAL, total_pav REAL",
        ].join(" "),
      },
      notes: [
        "Players have no team_id column — a player's team is determined per-game via player_match_stats.team_id.",
        "player_season_pav is available 1998 onwards only. Use LEFT JOIN when combining with player_match_stats — pre-1998 seasons have stats but no PAV rows.",
        "total_pav = off_pav + mid_pav + def_pav.",
        "PAV zone meanings: off_pav = offensive (goals, score involvements, forward craft); mid_pav = midfield (disposals, clearances, tackles, contested ball); def_pav = defensive (intercepts, spoils, one-percenters, rebounds).",
        "PAV interpretation: 25+ exceptional (Brownlow contention), 20-25 great (All-Australian), 15-20 very good (team best-22), 10-15 solid contributor, 5-10 below average or limited games, <5 minimal contribution. Zone PAV of 10+ = All-Australian contention in that role.",
        "Opening Round has round_number = 0. It is played before Round 1 and must not be excluded from queries.",
        "round_type distinguishes 'Regular' from finals rounds ('Finals', 'Qualifying Final', 'Elimination Final', 'Semi Final', 'Preliminary Final', 'Grand Final').",
        "match date format is ISO 8601 (YYYY-MM-DD).",
        "AFL Fantasy scores and Supercoach scores may be null for older matches (pre-2007).",
        "Data covers AFL Men's competition from 1990 to the current season.",
      ],
      common_joins: {
        team_roster_pav: [
          "SELECT p.first_name, p.surname, psp.off_pav, psp.mid_pav, psp.def_pav, psp.total_pav",
          "FROM player_season_pav psp",
          "JOIN players p ON psp.player_id = p.id",
          "JOIN seasons s ON psp.season_id = s.id",
          "JOIN teams t ON psp.team_id = t.id",
          "WHERE t.name = ? AND s.year = ?",
          "ORDER BY psp.total_pav DESC",
        ].join("\n"),
        player_career_arc: [
          "SELECT s.year, SUM(pms.disposals) as total_disposals, SUM(pms.goals) as total_goals,",
          "  COUNT(*) as games, psp.total_pav, psp.off_pav, psp.mid_pav, psp.def_pav",
          "FROM player_match_stats pms",
          "JOIN matches m ON pms.match_id = m.id",
          "JOIN seasons s ON m.season_id = s.id",
          "LEFT JOIN player_season_pav psp ON psp.player_id = pms.player_id AND psp.season_id = s.id",
          "WHERE pms.player_id = ?",
          "GROUP BY s.year, psp.total_pav, psp.off_pav, psp.mid_pav, psp.def_pav",
          "ORDER BY s.year",
        ].join("\n"),
        zone_leaders: [
          "SELECT p.first_name, p.surname, t.name as team, psp.mid_pav, psp.off_pav, psp.def_pav, psp.total_pav",
          "FROM player_season_pav psp",
          "JOIN players p ON psp.player_id = p.id",
          "JOIN seasons s ON psp.season_id = s.id",
          "JOIN teams t ON psp.team_id = t.id",
          "WHERE s.year = ?",
          "ORDER BY psp.total_pav DESC",
          "LIMIT 20",
        ].join("\n"),
        match_with_teams_venue: [
          "SELECT m.date, m.round, ht.name as home_team, at.name as away_team,",
          "  m.home_points, m.away_points, m.margin, v.name as venue",
          "FROM matches m",
          "JOIN teams ht ON m.home_team_id = ht.id",
          "JOIN teams at ON m.away_team_id = at.id",
          "JOIN venues v ON m.venue_id = v.id",
          "WHERE m.season_id = (SELECT id FROM seasons WHERE year = ?)",
        ].join("\n"),
      },
      ladder_example: [
        "// Computing the AFL ladder for a given season year and optional round",
        "const season = await db.prepare('SELECT id FROM seasons WHERE year = ?').bind(year).first()",
        "let sql = `",
        "  SELECT team_id, team_name,",
        "    COUNT(*) as played,",
        "    SUM(CASE WHEN result = 'W' THEN 1 ELSE 0 END) as wins,",
        "    SUM(CASE WHEN result = 'L' THEN 1 ELSE 0 END) as losses,",
        "    SUM(CASE WHEN result = 'D' THEN 1 ELSE 0 END) as draws,",
        "    SUM(points_for) as points_for,",
        "    SUM(points_against) as points_against,",
        "    ROUND(100.0 * SUM(points_for) / SUM(points_against), 2) as percentage,",
        "    SUM(CASE WHEN result = 'W' THEN 4 WHEN result = 'D' THEN 2 ELSE 0 END) as premiership_points",
        "  FROM (",
        "    SELECT m.home_team_id as team_id, ht.name as team_name,",
        "      m.home_points as points_for, m.away_points as points_against,",
        "      CASE WHEN m.home_points > m.away_points THEN 'W'",
        "           WHEN m.home_points < m.away_points THEN 'L' ELSE 'D' END as result",
        "    FROM matches m JOIN teams ht ON m.home_team_id = ht.id",
        "    WHERE m.season_id = ? AND m.round_type = 'Regular'",
        "    UNION ALL",
        "    SELECT m.away_team_id, at.name,",
        "      m.away_points, m.home_points,",
        "      CASE WHEN m.away_points > m.home_points THEN 'W'",
        "           WHEN m.away_points < m.home_points THEN 'L' ELSE 'D' END",
        "    FROM matches m JOIN teams at ON m.away_team_id = at.id",
        "    WHERE m.season_id = ? AND m.round_type = 'Regular'",
        "  ) GROUP BY team_id, team_name",
        "  ORDER BY premiership_points DESC, percentage DESC",
        "`",
        "// Bind season.id twice (once per UNION branch)",
        "const ladder = await db.prepare(sql).bind(season.id, season.id).all()",
        "return ladder.results",
      ].join("\n"),
    },
    query_api: {
      usage: "db.prepare(sql).bind(param1, param2, ...).all() returns { results: Row[] }. Use .first() for a single row.",
      methods: [
        "db.prepare(sql).bind(...args).all() — returns { results: Row[], success, meta }",
        "db.prepare(sql).bind(...args).first() — returns first Row or null",
        "db.prepare(sql).bind(...args).first(column) — returns single column value",
        "db.prepare(sql).bind(...args).raw() — returns array of arrays",
        "db.batch([stmt1, stmt2]) — run multiple statements in a transaction",
      ],
      notes: "Read-only. 30-second timeout. Use ? for parameter binding.",
    },
  }
}
